### ISSUE TITLE
MD_DS1307_LCD_Time.ino does not return Day Of Week

### ISSUE THREAD

**Issue by ghost** [MajicDesigns/MD_DS1307#3]
MD_DS1307_LCD_Time.ino dosen’t return DayofWeek

  lcd.print(dow2String(RTC.dow)); 

 this lines

  " RTC.dow " return 0  at always;
i guess this line must be 

 lcd.print(dow2String(RTC.calcDoW(RTC.yyyy, RTC.mm, RTC.dd))); 

anyway Thank you so much .
This library is good for me.

**Comment by MajicDesigns** [comment]
Tested and did not see this effect happening. The library returns the value from the RTC IC and 0 is not a valid number in the hardware (ie, it never set to 0) as the range is 1-7. A value of 0 is only set on initialisation and if this value is seen then it is possible that I2C comms is not established. This is not mentioned.
